Repository tldr-pages/extldr, pull requests merged in 2020-05, with the labels that each got.

#5 Add a Codacy badge to README.md
  README.md
Labels: documentation

#14 Update references to the repository
  README.md
  lib/ex_tldr.ex
Labels: documentation

#15 Add GitHub Actions workflow
  .github/workflows/ci.yml
Labels: enhancement

#17 gh-actions: fix ExCoveralls building
  .github/workflows/ci.yml
Labels: bug

#18 travis: remove configuration file
  .travis.yml
Labels: enhancement

#19 Update build status badge for GitHub Actions
  .github/workflows/ci.yml
  README.md
Labels: enhancement
